---
title: "Bug Reporting and Fixing"
output: html_document
---

```{r echo=FALSE, results='asis'}
# Define the news updates
news_updates <- list(
  list(date = "2025-12-16", title = "Bugs Fixed and Pass First Round of Test", content = "Initial Test Passed")
)

# Create dropdown menu
dropdown_menu <- function(news) {
  tags$div(
    class = "dropdown",
    tags$button(class = "btn btn-primary dropdown-toggle", type = "button", id = "dropdownMenuButton", `data-toggle` = "dropdown", `aria-haspopup` = "true", `aria-expanded` = "false", "Bug Report"),
    tags$div(class = "dropdown-menu", `aria-labelledby` = "dropdownMenuButton", 
      lapply(news, function(item) {
        tags$a(class = "dropdown-item", href = "#", item$title)
      })
    )
  )
}

# Render the dropdown menu
dropdown_menu(news_updates)
```

## Detailed Updates

```{r echo=FALSE, results='asis'}
# Display detailed news updates
for (item in news_updates) {
  cat(paste0("### ", item$title, "\n\n"))
  cat(paste0("**Date:** ", item$date, "\n\n"))
  cat(paste0(item$content, "\n\n"))
}
```
